// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARpvVhqzHY_gKwCqSphyjCuf0Ujqt2xEc',
    appId: '1:915166643849:web:9e6cfec1dab5713251a858',
    messagingSenderId: '915166643849',
    projectId: 'calendar-f61e7',
    authDomain: 'calendar-f61e7.firebaseapp.com',
    storageBucket: 'calendar-f61e7.firebasestorage.app',
    measurementId: 'G-HJNQD4212K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6DxkC-24CZsWm0j74Tfvpj6_jMsOEW2k',
    appId: '1:915166643849:android:17cc4179623522fb51a858',
    messagingSenderId: '915166643849',
    projectId: 'calendar-f61e7',
    storageBucket: 'calendar-f61e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhU3It0eAB11Q0y0sOn1AsFKhyfRZxXjE',
    appId: '1:915166643849:ios:effc42056543358751a858',
    messagingSenderId: '915166643849',
    projectId: 'calendar-f61e7',
    storageBucket: 'calendar-f61e7.firebasestorage.app',
    iosBundleId: 'com.example.calendarApp',
  );
}
